"use strict";
(self.webpackChunk_N_E=self.webpackChunk_N_E||[]).push([[8673],{15307:(e,t,n)=>{n.d(t,{$m:()=>v,EA:()=>d,OV:()=>p,OW:()=>f,Pt:()=>b,Xb:()=>m,ZQ:()=>h,uA:()=>x,zY:()=>c,zk:()=>u});
var r=n(95155),i=n(78773),l=n(51606),a=n(40209),o=n(7550);
n(20467);
var s=n(93474);
function c(e){let{title:t,subtitle:n,right:i}=e;
return(0,r.jsxs)("div",{className:"mb-6 flex flex-wrap items-end justify-between gap-3",children:[(0,r.jsxs)("div",{children:[(0,r.jsx)("h1",{className:"text-xl font-bold tracking-tight",children:t}),n&&(0,r.jsx)("p",{className:"mt-1 text-sm text-ink-dim",children:n})]}),i]})}function u(e){let{state:t}=e;
return(0,r.jsx)("span",{className:"inline-block h-2 w-2 rounded-full ".concat("fresh"===t?"bg-emerald-400":"stale"===t?"bg-amber-400":"bg-red-400"," ").concat("fresh"===t?"pulse-dot":"")})}function d(e){let{className:t=""}=e;
return(0,r.jsx)("div",{className:"skeleton ".concat(t)})}function m(e){let{onRetry:t,message:n}=e,{t:a}=(0,s.s)();
return(0,r.jsxs)("div",{className:"panel flex flex-col items-center gap-3 p-10 text-center",children:[(0,r.jsx)(i.A,{size:22,className:"text-ink-faint"}),(0,r.jsx)("p",{className:"text-sm text-ink-dim",children:n||a.loadError}),t&&(0,r.jsxs)("button",{onClick:t,className:"flex items-center gap-2 rounded-lg border border-edge px-4 py-2 text-xs font-medium text-ink-dim hover:border-accent/40 hover:text-ink",children:[(0,r.jsx)(l.A,{size:12})," ",a.retry]})]})}function f(e){let{data:t,width:n=60,height:i=22,strokeUp:l="#34d399",strokeDown:a="#f87171"}=e,o=(null!=t?t:[]).filter(e=>Number.isFinite(e));
if(o.length<2)return(0,r.jsx)("div",{style:{width:n,height:i}});
let s=Math.min(...o),c=Math.max(...o),u=c-s<1e-9,d=u?1:c-s,m=o.map((e,t)=>{let r=t/(o.length-1)*(n-2)+1,l=u?i/2:i-2-(e-s)/d*(i-4);
return"".concat(r.toFixed(1),",").concat(l.toFixed(1))}).join(" "),f=o[o.length-1]>=o[0];
return(0,r.jsx)("svg",{width:n,height:i,className:u?"shrink-0 text-ink-faint":"shrink-0",children:(0,r.jsx)("polyline",{points:m,fill:"none",stroke:u?"currentColor":f?l:a,strokeWidth:"1.5",strokeLinejoin:"round"})})}function h(e){let{value:t}=e;
return(0,r.jsxs)("div",{className:"flex items-center gap-2",children:[(0,r.jsx)("div",{className:"h-1.5 w-16 overflow-hidden rounded-full bg-panel-2",children:(0,r.jsx)("div",{className:"h-full rounded-full ".concat(t>=70?"bg-emerald-400":t>=50?"bg-amber-400":"bg-red-400"),style:{width:"".concat(Math.min(100,t),"%")}})}),(0,r.jsx)("span",{className:"num text-xs text-ink-dim",children:Math.round(t)})]})}function x(e){let{value:t,label:n,size:i=180,decimals:l=0,zones:a=[[0,25,"#ef4444"],[25,45,"#f59e0b"],[45,55,"#94a3b8"],[55,75,"#84cc16"],[75,100,"#10b981"]]}=e,o=i/2,s=i/2,c=i/2-14,u=e=>Math.PI*(1-e/100),d=function(e){let t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:c;
return{x:o+t*Math.cos(u(e)),y:s-t*Math.sin(u(e))}},m=d(Math.max(0,Math.min(100,t)),c-10);
return(0,r.jsxs)("svg",{viewBox:"0 0 ".concat(i," ").concat(i/2+24),width:"100%",style:{maxWidth:i},preserveAspectRatio:"xMidYMid meet",className:"overflow-visible",children:[a.map(e=>{let[t,n,i]=e,l=d(t),a=d(n),o=+(n-t>50);
return(0,r.jsx)("path",{d:"M ".concat(l.x," ").concat(l.y," A ").concat(c," ").concat(c," 0 ").concat(o," 1 ").concat(a.x," ").concat(a.y),fill:"none",stroke:i,strokeWidth:9,strokeLinecap:"butt",opacity:.85},"".concat(t,"-").concat(n))}),(0,r.jsx)("line",{x1:o,y1:s,x2:m.x,y2:m.y,stroke:"#e2e8f0",strokeWidth:2.5,strokeLinecap:"round"}),(0,r.jsx)("circle",{cx:o,cy:s,r:4.5,fill:"#e2e8f0"}),(0,r.jsx)("text",{x:o,y:s-c/2.4,textAnchor:"middle",className:"num",fill:"#f1f5f9",fontSize:i/7,fontWeight:700,children:l>0?t.toFixed(l):Math.round(t)}),n&&(0,r.jsx)("text",{x:o,y:s+20,textAnchor:"middle",fill:"#8b9bb4",fontSize:12,children:n})]})}let g={low:"bg-sky-500/15 text-sky-400 border-sky-500/30",medium:"bg-amber-500/15 text-amber-400 border-amber-500/30",high:"bg-orange-500/15 text-orange-400 border-orange-500/30",critical:"bg-red-500/15 text-red-400 border-red-500/30"};
function b(e){var t;
let{severity:n}=e;
return(0,r.jsx)("span",{className:"rounded border px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide ".concat(null!=(t=g[n])?t:g.low),children:n})}function p(e){let{score:t}=e;
return(0,r.jsx)("span",{className:"num rounded px-1.5 py-0.5 text-[11px] font-bold ".concat(t>=70?"bg-red-500/15 text-red-400":t>=45?"bg-orange-500/15 text-orange-400":t>=20?"bg-amber-500/15 text-amber-400":"bg-slate-600/20 text-slate-400"),children:Math.round(t)})}function v(e){let{direction:t}=e,n="long"===t;
return(0,r.jsxs)("span",{className:"inline-flex items-center gap-0.5 rounded px-1.5 py-0.5 text-[11px] font-bold uppercase ".concat(n?"bg-emerald-500/15 text-emerald-400":"bg-red-500/15 text-red-400"),children:[n?(0,r.jsx)(a.A,{size:11,strokeWidth:2.6}):(0,r.jsx)(o.A,{size:11,strokeWidth:2.6}),t]})}},20467:(e,t,n)=>{function r(e){let t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:2;
return null!=e&&Number.isFinite(e)?e.toLocaleString("en-US",{minimumFractionDigits:t,maximumFractionDigits:t}):"—"}function i(e){if(null==e||!Number.isFinite(e))return"—";
let t=Math.abs(e);
return t>=1e3?r(e,0):t>=10?r(e,2):r(e,4)}function l(e){let t=!(arguments.length>1)||void 0===arguments[1]||arguments[1];
if(null==e||!Number.isFinite(e))return"—";
let n=t&&e>0?"+":"";
return"".concat(n).concat(e.toFixed(2),"%")}function a(e){let t=!(arguments.length>1)||void 0===arguments[1]||arguments[1];
if(null==e||!Number.isFinite(e))return"—";
let n=t&&e>0?"+":"";
return"".concat(n).concat(e.toFixed(1),"bp")}function o(e,t){if(null==e)return"—";
switch(t){case"%":return"".concat(r(e,3),"%");
case"bps":return"".concat(r(e,0)," bps");
case"$B":return"$".concat(r(e,1),"B");
case"USD":return"$".concat(i(e));
default:return i(e)}}function s(e){var t;
let n=arguments.length>1&&void 0!==arguments[1]?arguments[1]:"realtime";
if(!e)return"old";
let r=(Date.now()-new Date(e).getTime())/36e5,i={realtime:[2,24],daily:[30,96],sparse:[96,336],manual:[2880,9600]},[l,a]=null!=(t=i[n])?t:i.realtime;
return r<l?"fresh":r<a?"stale":"old"}function c(e,t,n){if(!n)return"old";
let r=e.toLowerCase(),i=(null!=t?t:"").toLowerCase(),l=(Date.now()-new Date(n).getTime())/864e5,[a,o]=/(_debt_gdp|_ca_gdp|_fiscal_deficit|_household_debt)$/.test(r)||/_rating_/.test(r)?[400,550]:/_policy_rate$/.test(r)?[75,130]:/(_cpi_yoy|_core_cpi|_pce_yoy)$/.test(r)||"inflation"===i?[50,85]:/(_reserves|_unemployment)$/.test(r)?[70,130]:"banking"===i||/^cot_/.test(r)||/_auction_btc$/.test(r)?[12,24]:"yield"===i||"fx"===i||"volatility"===i||"commodity"===i||"policy"===i||"credit"===i?[4,10]:[10,20];
return l<a?"fresh":l<o?"stale":"old"}function u(e){let t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:"th";
if(!e)return"—";
let n=Math.floor((Date.now()-new Date(e).getTime())/6e4);
if(n<1)return"th"===t?"เมื่อสักครู่":"just now";
if(n<60)return"th"===t?"".concat(n," นาทีที่แล้ว"):"".concat(n,"m ago");
let r=Math.floor(n/60);
if(r<24)return"th"===t?"".concat(r," ชม.ที่แล้ว"):"".concat(r,"h ago");
let i=Math.floor(r/24);
return"th"===t?"".concat(i," วันที่แล้ว"):"".concat(i,"d ago")}n.d(t,{I9:()=>s,PB:()=>o,SJ:()=>g,_E:()=>r,d7:()=>d,ex:()=>a,fF:()=>u,io:()=>c,o:()=>v,pT:()=>l,q_:()=>b,v7:()=>m,wY:()=>x,xe:()=>i});
let d=e=>null==e?"text-slate-500":e>0?"text-emerald-400":e<0?"text-red-400":"text-slate-400";
function m(e){return e&&/^https?:\/\//i.test(e)?e:void 0}let f="Asia/Bangkok",h=new Intl.DateTimeFormat("en-CA",{timeZone:f,year:"numeric",month:"2-digit",day:"2-digit"});
function x(e){let t=e instanceof Date?e:new Date(e);
return Number.isNaN(t.getTime())?"—":h.format(t)}function g(){let e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:Date.now(),t=e+252e5,n=new Date(t).getUTCDay();
return new Date(t-(n+6)%7*864e5).toISOString().slice(0,10)}function b(e,t,n){if(null==e)return"—";
let r=new Date(e);
return Number.isNaN(r.getTime())?"—":r.toLocaleString("th"===t?"th-TH":"en-US",{...n,timeZone:f})}let p=new Intl.DateTimeFormat("sv-SE",{timeZone:f,dateStyle:"short",timeStyle:"short"});
function v(e){let t=e instanceof Date?e:new Date(e);
return Number.isNaN(t.getTime())?"—":p.format(t)}},62890:(e,t,n)=>{n.d(t,{ND:()=>c,VI:()=>u,m5:()=>d});
var r,i,l=n(58247),a=n(95704);
let o=null!=(r=a.env.NEXT_PUBLIC_SUPABASE_URL)?r:"https://vovprwjjauwqqiowwgqd.supabase.co",s=null!=(i=a.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)?i:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvdnByd2pqYXV3cXFpb3d3Z3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM4MzYwNzYsImV4cCI6MjA5OTQxMjA3Nn0.tzQD850ui-w8zPFwldzVXzMu5ERwlJvkwHleAvq7NII",c=(0,l.UU)(o,s,{auth:{persistSession:!0,autoRefreshToken:!0,detectSessionInUrl:!0,flowType:"pkce"}}),u=o,d=s},76924:(e,t,n)=>{n.d(t,{A:()=>u,AuthProvider:()=>c});
var r,i=n(95155),l=n(12115),a=n(62890);
let o=(null!=(r=n(95704).env.NEXT_PUBLIC_ADMIN_EMAILS)?r:"natdanaic9510@gmail.com").split(",").map(e=>e.trim().toLowerCase()).filter(Boolean),s=(0,l.createContext)({session:null,user:null,loading:!0,isAdmin:!1,isRoot:!1,banned:!1,needsOnboarding:!1,refreshProfile:()=>{},signInWithGoogle:()=>{},signOut:()=>{}});
function c(e){var t,n,r,c;
let{children:u}=e,[d,m]=(0,l.useState)(null),[f,h]=(0,l.useState)(!0),[x,g]=(0,l.useState)(null),[b,p]=(0,l.useState)(!1);
(0,l.useEffect)(()=>{a.ND.auth.getSession().then(e=>{let{data:t}=e;
m(t.session),h(!1)});
let{data:e}=a.ND.auth.onAuthStateChange((e,t)=>{m(t),h(!1)});
return()=>e.subscription.unsubscribe()},[]);
let v=null!=(r=null==d||null==(t=d.user)?void 0:t.id)?r:null,w=(0,l.useCallback)(async e=>{let{data:t}=await a.ND.from("user_profiles").select("role, banned, onboarded_at").eq("user_id",e).maybeSingle();
return null!=t?t:null},[]);
(0,l.useEffect)(()=>{if(!v){g(null),p(!1);
return}let e=!1;
return p(!1),w(v).then(t=>{e||(g(t),p(!0))}),()=>{e=!0}},[v,w]);
let N=(0,l.useCallback)(()=>{v&&w(v).then(e=>g(e))},[v,w]),y=!!(null==d||null==(n=d.user)?void 0:n.email)&&o.includes(d.user.email.toLowerCase()),k=y||(null==x?void 0:x.role)==="admin"&&!(null==x?void 0:x.banned),_=!y&&(null==x?void 0:x.banned)===!0,j=!!d&&!y&&!_&&b&&!(null==x?void 0:x.onboarded_at);
return(0,i.jsx)(s.Provider,{value:{session:d,user:null!=(c=null==d?void 0:d.user)?c:null,loading:f,isAdmin:k,isRoot:y,banned:_,needsOnboarding:j,refreshProfile:N,signInWithGoogle:()=>{a.ND.auth.signInWithOAuth({provider:"google",options:{redirectTo:"".concat(window.location.origin).concat(window.location.pathname)}})},signOut:()=>{a.ND.auth.signOut()}},children:u})}function u(){return(0,l.useContext)(s)}},77823:(e,t,n)=>{n.d(t,{E:()=>o});
var r=n(12115),i=n(20063),l=n(76924),a=n(92077);
function o(e){var t;
let n=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{},{refreshMs:o,deps:s=[]}=n,c=function(){let e=(0,i.usePathname)(),{session:t,isAdmin:n,loading:r}=(0,l.A)();
return"/"!==e&&(!!r||!t||(0,a.f)(e)&&!n)}(),u=(null==(t=n.enabled)||t)&&!c,[d,m]=(0,r.useState)(null),[f,h]=(0,r.useState)(!0),[x,g]=(0,r.useState)(null),b=(0,r.useRef)(e);
b.current=e;
let p=(0,r.useRef)(0),v=(0,r.useRef)(0),w=(0,r.useCallback)(async()=>{let e=++p.current;
try{let t=await b.current();
if(e!==p.current)return;
m(t),g(null),v.current=0}catch(t){if(e!==p.current)return;
g(t instanceof Error?t.message:String(t)),v.current++}finally{e===p.current&&h(!1)}},[]);
return(0,r.useEffect)(()=>{if(!u)return;
h(!0),v.current=0;
let e=null,t=!1,n=async()=>{if(await w(),!t&&o){var r;
e=setTimeout(n,(r=v.current,!Number.isFinite(o)||o<=0?0:r<=0?o:Math.min(o*2**Math.min(r,20),3e5)))}};
return n(),()=>{t=!0,e&&clearTimeout(e),p.current++}},[o,w,u,...s]),{data:d,loading:f,error:x,reload:w}}},92077:(e,t,n)=>{n.d(t,{f:()=>i});
let r=["/backtest","/members","/tokens","/trade-desk/settings","/trade-desk/meetings","/boardroom/settings","/boardroom/memory","/boardroom/knowledge","/boardroom/stats","/boardroom/data-gaps","/countries/coverage"];
function i(e){return r.some(t=>e===t||e.startsWith(t+"/"))}}}]);
