"""initial 26-table schema

Revision ID: fdb64c353441
Revises: 
Create Date: 2026-08-11 00:49:39.151031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = 'fdb64c353441'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boardroom_claims',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('seat_id', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(), nullable=True),
    sa.Column('expected', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('sub_reason', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('checks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boardroom_claims_meeting_id'), 'boardroom_claims', ['meeting_id'], unique=False)
    op.create_table('boardroom_knowledge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('as_of', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('votes', sa.Text(), nullable=True),
    sa.Column('supersedes', sa.String(), nullable=True),
    sa.Column('superseded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boardroom_meetings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('current_turn', sa.Integer(), nullable=False),
    sa.Column('turn_plan', sa.Text(), nullable=False),
    sa.Column('agenda', sa.Text(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('trigger_key', sa.String(length=256), nullable=True),
    sa.Column('resolution_md', sa.Text(), nullable=True),
    sa.Column('resolution_json', sa.Text(), nullable=True),
    sa.Column('snapshot', sa.Text(), nullable=True),
    sa.Column('claim_until', sa.DateTime(), nullable=True),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boardroom_meetings_trigger_key'), 'boardroom_meetings', ['trigger_key'], unique=False)
    op.create_table('boardroom_memory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('statement_md', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_meeting_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('last_checked_meeting_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boardroom_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('seat_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boardroom_messages_meeting_id'), 'boardroom_messages', ['meeting_id'], unique=False)
    op.create_table('boardroom_seat_stats',
    sa.Column('seat_id', sa.String(), nullable=False),
    sa.Column('meetings', sa.Integer(), nullable=False),
    sa.Column('claims_total', sa.Integer(), nullable=False),
    sa.Column('claims_verified', sa.Integer(), nullable=False),
    sa.Column('claims_partial', sa.Integer(), nullable=False),
    sa.Column('claims_failed', sa.Integer(), nullable=False),
    sa.Column('stances_total', sa.Integer(), nullable=False),
    sa.Column('stances_correct', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('seat_id')
    )
    op.create_table('boardroom_seats',
    sa.Column('seat_id', sa.String(), nullable=False),
    sa.Column('position_key', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('name_th', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('seat_id')
    )
    op.create_table('boardroom_stances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('stance_index', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=64), nullable=False),
    sa.Column('price_key', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('price_at', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('consensus', sa.String(length=16), nullable=True),
    sa.Column('qualified', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('unit_mismatch', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boardroom_stances_meeting_id'), 'boardroom_stances', ['meeting_id'], unique=False)
    op.create_table('boardroom_trigger_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.String(), nullable=True),
    sa.Column('meeting_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boardroom_trigger_log_checked_at'), 'boardroom_trigger_log', ['checked_at'], unique=False)
    op.create_table('boardroom_unresolved_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset', sa.String(length=64), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_tried_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boardroom_unresolved_assets_asset'), 'boardroom_unresolved_assets', ['asset'], unique=False)
    op.create_table('country_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=4), nullable=False),
    sa.Column('brief_md', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('scenarios', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_briefs_country_code'), 'country_briefs', ['country_code'], unique=False)
    op.create_table('country_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=4), nullable=False),
    sa.Column('report_md', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_reports_country_code'), 'country_reports', ['country_code'], unique=False)
    op.create_table('manual_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('range', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_score_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_score_history_recorded_at'), 'model_score_history', ['recorded_at'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('impact_score', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title_th', sa.String(length=500), nullable=True),
    sa.Column('analysis_th', sa.Text(), nullable=True),
    sa.Column('related_models', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cash_usd', sa.Float(), nullable=False),
    sa.Column('target_allocation_pct', sa.Float(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screener_stocks',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('peg', sa.Float(), nullable=True),
    sa.Column('ps', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('div_yield', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roic', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('profit_margin', sa.Float(), nullable=True),
    sa.Column('de_ratio', sa.Float(), nullable=True),
    sa.Column('p_fcf', sa.Float(), nullable=True),
    sa.Column('ev_sales', sa.Float(), nullable=True),
    sa.Column('upside_pct', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('refreshed_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('trade_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_on', sa.Boolean(), nullable=True),
    sa.Column('per_team_daily_cap', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name_th', sa.String(length=64), nullable=True),
    sa.Column('name_en', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('capital', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('weekly_target_pct', sa.Float(), nullable=True),
    sa.Column('monthly_floor_pct', sa.Float(), nullable=True),
    sa.Column('monthly_stretch_pct', sa.Float(), nullable=True),
    sa.Column('interval_hours', sa.Integer(), nullable=True),
    sa.Column('next_turn_at', sa.DateTime(), nullable=True),
    sa.Column('directive_md', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('trading_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('tp', sa.Float(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('signal_strength', sa.Integer(), nullable=False),
    sa.Column('strength_factors', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=64), nullable=True),
    sa.Column('rationale_th', sa.Text(), nullable=True),
    sa.Column('rationale_en', sa.Text(), nullable=True),
    sa.Column('ta_snapshot', sa.Text(), nullable=True),
    sa.Column('sparkline', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_signals_asset'), 'trading_signals', ['asset'], unique=False)
    op.create_index(op.f('ix_trading_signals_created_at'), 'trading_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_trading_signals_model_id'), 'trading_signals', ['model_id'], unique=False)
    op.create_index(op.f('ix_trading_signals_status'), 'trading_signals', ['status'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('avg_cost_usd', sa.Float(), nullable=False),
    sa.Column('target_allocation_pct', sa.Float(), nullable=True),
    sa.Column('realized_pnl_usd', sa.Float(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('market', sa.String(length=32), nullable=True),
    sa.Column('unit', sa.String(length=8), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('margin_usd', sa.Float(), nullable=True),
    sa.Column('entry_px', sa.Float(), nullable=True),
    sa.Column('sl_pct', sa.Float(), nullable=True),
    sa.Column('tp_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('close_px', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['trade_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_positions_team_id'), 'trade_positions', ['team_id'], unique=False)
    op.create_table('trade_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('snapped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['trade_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_snapshots_team_id'), 'trade_snapshots', ['team_id'], unique=False)
    op.create_table('trade_turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('lead_decision', sa.Text(), nullable=True),
    sa.Column('seat_orders', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['trade_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_turns_team_id'), 'trade_turns', ['team_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_index(op.f('ix_trade_turns_team_id'), table_name='trade_turns')
    op.drop_table('trade_turns')
    op.drop_index(op.f('ix_trade_snapshots_team_id'), table_name='trade_snapshots')
    op.drop_table('trade_snapshots')
    op.drop_index(op.f('ix_trade_positions_team_id'), table_name='trade_positions')
    op.drop_table('trade_positions')
    op.drop_table('holdings')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_trading_signals_status'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_model_id'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_created_at'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_asset'), table_name='trading_signals')
    op.drop_table('trading_signals')
    op.drop_table('trade_teams')
    op.drop_table('trade_settings')
    op.drop_table('screener_stocks')
    op.drop_table('portfolios')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_model_score_history_recorded_at'), table_name='model_score_history')
    op.drop_table('model_score_history')
    op.drop_table('manual_zones')
    op.drop_index(op.f('ix_country_reports_country_code'), table_name='country_reports')
    op.drop_table('country_reports')
    op.drop_index(op.f('ix_country_briefs_country_code'), table_name='country_briefs')
    op.drop_table('country_briefs')
    op.drop_index(op.f('ix_boardroom_unresolved_assets_asset'), table_name='boardroom_unresolved_assets')
    op.drop_table('boardroom_unresolved_assets')
    op.drop_index(op.f('ix_boardroom_trigger_log_checked_at'), table_name='boardroom_trigger_log')
    op.drop_table('boardroom_trigger_log')
    op.drop_index(op.f('ix_boardroom_stances_meeting_id'), table_name='boardroom_stances')
    op.drop_table('boardroom_stances')
    op.drop_table('boardroom_seats')
    op.drop_table('boardroom_seat_stats')
    op.drop_index(op.f('ix_boardroom_messages_meeting_id'), table_name='boardroom_messages')
    op.drop_table('boardroom_messages')
    op.drop_table('boardroom_memory')
    op.drop_index(op.f('ix_boardroom_meetings_trigger_key'), table_name='boardroom_meetings')
    op.drop_table('boardroom_meetings')
    op.drop_table('boardroom_knowledge')
    op.drop_index(op.f('ix_boardroom_claims_meeting_id'), table_name='boardroom_claims')
    op.drop_table('boardroom_claims')
    # ### end Alembic commands ###
